---
title: "R Project 1 - Hello R"
author: "*Muhammad Waleed Jamal*"
date: "9/16/2020"
output: 
  html_document: 
    toc: yes
    toc_depth: 4
    fig_width: 10
    fig_height: 10
---


### Loading the packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


## Exercise 1
```
A data frame with 1846 rows and 3 variables:

dataset: indicates which dataset the data are from

x: x-values

y: y-values
```
## Exercise 2
### The Big Dinosaur 
```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```


```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```


## Exercise 3

### This plots a star on the graph. 


```{r plot.stars, fig.height=4,fig.width=7}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data=dino_data,mapping=aes(x=x,y=y))+
  geom_point()

```

```{r cor-star}
dino_data %>%
  summarize(r=cor(x,y ))
```
## Exercise 4

### This is a circle plot.
```{r plot.circles, fig.height=15, fig.width=8}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data=dino_data,mapping=aes(x=x,y=y))+
  geom_point()
```

```{r cor-circle}
dino_data %>%
  summarize (r=cor(x,y))
```





## Exercise 5

### This code plots graphs from each different dataset
```{r plot}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
geom_point()+
facet_wrap(~ dataset, ncol = 3) + # facet the dataset variable, in 3 cols
theme(legend.position = "none")
```